[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools >= 43.0.0',
    'numpy',
]

[pytest]
markers = [
    "context_dependent: marks test as one that depends on the execution context",
]
